name: easy_flutter_downloader
description: "Easy-to-use Flutter download manager with platform-aware file saving."
version: 0.0.1
homepage: https://github.com/reyn-flores/easy_downloader
repository: https://github.com/reyn-flores/easy_downloader

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.7.0
  downloadsfolder: ^1.2.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  gal: ^2.3.1
  path_provider: ^2.1.5
  uuid: ^4.5.1
  
dev_dependencies:
  test: ^1.29.0
  very_good_analysis: ^7.0.0